/* tslint:disable */
require("./styles.module.css");
const styles = {
  fab: 'fab_de2a6ffa',
  panel: 'panel_de2a6ffa',
  header: 'header_de2a6ffa',
  headerTop: 'headerTop_de2a6ffa',
  aiLogo: 'aiLogo_de2a6ffa',
  headerInfo: 'headerInfo_de2a6ffa',
  headerTitle: 'headerTitle_de2a6ffa',
  headerSubtitle: 'headerSubtitle_de2a6ffa',
  closeBtn: 'closeBtn_de2a6ffa',
  modeRow: 'modeRow_de2a6ffa',
  modeChip: 'modeChip_de2a6ffa',
  modeChipActive: 'modeChipActive_de2a6ffa',
  chatArea: 'chatArea_de2a6ffa',
  welcome: 'welcome_de2a6ffa',
  fadeUp: 'fadeUp_de2a6ffa',
  welcomeLogo: 'welcomeLogo_de2a6ffa',
  welcomeTitle: 'welcomeTitle_de2a6ffa',
  welcomeText: 'welcomeText_de2a6ffa',
  suggestionGrid: 'suggestionGrid_de2a6ffa',
  suggestionCard: 'suggestionCard_de2a6ffa',
  suggestionIcon: 'suggestionIcon_de2a6ffa',
  suggestionText: 'suggestionText_de2a6ffa',
  msgRow: 'msgRow_de2a6ffa',
  userRow: 'userRow_de2a6ffa',
  avatar: 'avatar_de2a6ffa',
  aiAvatar: 'aiAvatar_de2a6ffa',
  userAvatar: 'userAvatar_de2a6ffa',
  bubble: 'bubble_de2a6ffa',
  userBubble: 'userBubble_de2a6ffa',
  aiBubble: 'aiBubble_de2a6ffa',
  mdContent: 'mdContent_de2a6ffa',
  msgTime: 'msgTime_de2a6ffa',
  userTime: 'userTime_de2a6ffa',
  typingRow: 'typingRow_de2a6ffa',
  typingBubble: 'typingBubble_de2a6ffa',
  typingDot: 'typingDot_de2a6ffa',
  dotBounce: 'dotBounce_de2a6ffa',
  errorBubble: 'errorBubble_de2a6ffa',
  emailCard: 'emailCard_de2a6ffa',
  emailCardHeader: 'emailCardHeader_de2a6ffa',
  emailCardBody: 'emailCardBody_de2a6ffa',
  emailField: 'emailField_de2a6ffa',
  emailLabel: 'emailLabel_de2a6ffa',
  emailValue: 'emailValue_de2a6ffa',
  emailBody: 'emailBody_de2a6ffa',
  emailEditInput: 'emailEditInput_de2a6ffa',
  emailEditTextarea: 'emailEditTextarea_de2a6ffa',
  emailActions: 'emailActions_de2a6ffa',
  successCard: 'successCard_de2a6ffa',
  successIcon: 'successIcon_de2a6ffa',
  bounceIn: 'bounceIn_de2a6ffa',
  successTitle: 'successTitle_de2a6ffa',
  successSub: 'successSub_de2a6ffa',
  btnPrimary: 'btnPrimary_de2a6ffa',
  btnOutline: 'btnOutline_de2a6ffa',
  btnDanger: 'btnDanger_de2a6ffa',
  inputArea: 'inputArea_de2a6ffa',
  inputHint: 'inputHint_de2a6ffa',
  inputRow: 'inputRow_de2a6ffa',
  chatInput: 'chatInput_de2a6ffa',
  sendBtn: 'sendBtn_de2a6ffa'
};

export default styles;
/* tslint:enable */